# This is a basic workflow to help you get started with Actions

name: CI-CD-Pipeline-to-AWS-ElastikBeastalk
env:
 EB_PACKAGE_S3_BUCKET_NAME: "my-flask-app-packages"
 EB_APP_NAME: "My-Flask"
 EB_ENV_NAME: "My-Flask-env"
 DEPLOY_PACKAGE_NAME: "flask_app_${{ github.sha }}.zip"
 AWS_REGION_NAME: "eu-north-1"
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my_ci_part:
    runs-on: ubuntu-latest
    
    steps:
      - name: Cit Clone our repo
        uses: actions/checkout@v1
      
      
      - name: Create zip deployment package
        run: zip -r ${{env.DEPLOY_PACKAGE_NAME}} ./ -x *.git
       
      
